### ISSUE TITLE
please make browser extention to work remotely of this project

### ISSUE THREAD

**Issue by bugbounted** [ajmandourah/Deep-reCaptcha#3]
Hi [ajmandourah](https://github.com/ajmandourah),
at the first special thanks for your special works,
please make browser extention to work remotely of this project because i want to deploy man project on cloud containers like heroku , render or ... & using cloud base power for solve captchas .
waiting for your response
finest regards

**Comment by ajmandourah** [comment]
Hey, Unfortunately such idea is not planned. this is a prove of concept and I am not planning to work on an extension and such. 
You on the other hand have the source file and the model . so feel free to experiment .
