### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by harusurv** [ajmandourah/Deep-reCaptcha#5]
I have read your description, but if you can place the training code to see the model build and everything for learning how you placed it and look for improvements and train my own model would be awesome. Thank you in advance.

**Comment by ajmandourah** [comment]
I suggest you read a liitle more about Tensorflow or watch some videos. I already provided the way i trained the model . the dataset i used is a generic one in addition to some i already collected from google. these all availabel at huggingface .
